- workstation/dom0/f25/securedrop-workstation-dom0-config-0.2.0-1.fc25.noarch.rpm
This is the final piece that will allow us to test production flows for the workstation. Build logs are available in https://github.com/freedomofpress/build-logs/commit/b2af83d527bc531d14292715d0763ba3d981276e
- In securedrop-workstation repo:
> Adds securedrop-workstation-dom0-config 0.2.0

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.2.1-1.fc25.noarch.rpm
Adds provisioning fixes discovered during the first release: https://github.com/freedomofpress/securedrop-workstation/pull/468
Build logs available here: https://github.com/freedomofpress/build-logs/commit/f38a8b6b9723da56ffe976f40bde2d654e7c6246
- In securedrop-workstation repo:
> securedrop-workstation-dom0-config 0.2.1

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.2.2-1.fc25.noarch.rpm
Build logs: https://github.com/freedomofpress/build-logs/commit/36ac40a24345310cca57f6598dc3e96e8e88a12f
- In securedrop-workstation repo:
> securedrop-workstation-dom0-config 0.2.2

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.2.3-1.fc25.noarch.rpm
Build logs: https://github.com/freedomofpress/build-logs/commit/b45d628057255d9ea828c71afe3768131c25a906
- In securedrop-workstation repo:
> Release securedrop-workstation-dom0-config 0.2.3

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.3.0-1.fc25.noarch.rpm
Build logs: https://github.com/freedomofpress/build-logs/commit/5c99f38366db27840546109beb9150ce557aa92e
> Release Securedrop Workstation dom0 0.3.0 config RPM

- .github/pull_request_template.md
Matches changes presented in the dev RPM repo [0],
porting here to reduce the copy/paste workflow when adding packages.
[0] https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/12
> Adds PR template for prod LFS packages

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.3.1-1.fc25.noarch.rpm
> securedrop-workstation-dom0-config 0.3.1

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.4.0-1.fc25.noarch.rpm
> Add securedrop-workstation-dom0-config 0.4.0

- workstation/dom0/f25/qubes-template-securedrop-workstation-buster-4.0.1-202007062239.noarch.rpm
###
Name of package: `qubes-template-securedrop-workstation-buster`
This is version 202007062239 of the SDW template, which bundles the 'securedrop-keyring' package at build time. The RPM is the same artifact originally submitted in https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/15
> Promotes Workstation TemplateVM RPM to prod

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.0-1.fc25.noarch.rpm
Towards https://github.com/freedomofpress/securedrop-workstation/issues/624
> Release securedrop-workstation-dom0-config 0.5.0

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.1-1.fc25.noarch.rpm
> Adds securedrop-workstation-dom0-config 0.5.1

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.2-1.fc25.noarch.rpm
> Adds securedrop-workstation-dom0-config 0.5.2

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.3-1.fc25.noarch.rpm
###
This is the same artifact presented in https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/22, resigned with prod key for promotion to prod.
> Adds securedrop-workstation-dom0-config 0.5.3

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.4-1.fc25.noarch.rpm
###
Signed with the current release key, i.e.
22245C81E3BAEB4138B36061310F561200F4AD77,
which is set to expire on 2021-06-30.
We'll follow up with a subsequent release
to finalize the key rotation.
> Add sdw-dom0-config 0.5.4 RPM

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.5-1.fc25.noarch.rpm
###
Includes changes from:
* https://github.com/freedomofpress/securedrop-workstation/pull/707
* https://github.com/freedomofpress/securedrop-workstation/pull/708
Signed with the old/current key, i.e.
22245C81E3BAEB4138B36061310F561200F4AD77
> Adds sdw-config 0.5.5 rpm

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.5-1.fc25.noarch.rpm
###
As part of the 2021 key rotation, we'll simply re-sign the existing RPM
for v0.5.5 with the new key, to simplify the first run story.
In the near future, we'll release a new version and make sure that's
signed, but until that's done, we can still ensure that the prod repo's
most recent versions are all properly signed with the new key.
Refs https://github.com/freedomofpress/securedrop-workstation/issues/714#issuecomment-892829531
> Resigns sdw-dom0-config 0.5.5 with new key

- .github/pull_request_template.md
Updates the PR template with more informative docs.
Require use of Debian Stable. Technically I've only tested with
Buster, which has 4.14.2.1+dfsg1-1 at time of writing. Perhaps Bullseye
will break things for us. For certain, the `rpm` in recent versions of
Fedora doesn't revert to the original checksum when running delsign.
Haven't investigated why.
> Tweak PR docs for rpm delsign invocations

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.6-1.fc25.noarch.rpm
###
Name of package: `securedrop-workstation-dom0-config`, v0.5.6
> Adds sdw-config 0.5.6 rpm

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.5.7-1.fc25.noarch.rpm
###
Same RPM as submitted in https://github.com/freedomofpress/securedrop-workstation-prod-rpm-packages-lfs/pull/23 , but resigned with the prod key. 
Towards https://github.com/freedomofpress/securedrop-workstation/issues/737
> Adds sdw-config 0.5.7 rpm

- .circleci/config.yml
CI was failing; this change implements the same update as
https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/31
Verify that CI is passing; that's enough for merge.
> Use debian:buster CI image

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.6.0-1.fc25.noarch.rpm
###
Adds the same RPM as submitted in https://github.com/freedomofpress/securedrop-workstation-prod-rpm-packages-lfs/pull/23, but resigned with the prod key. 
Closes https://github.com/freedomofpress/securedrop-workstation/issues/760
The RPM has already been checked via https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/30, so the rest of the checks are around it being signed with the prod key.
> add sdw-config 0.6.0 rpm

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.6.1-1.fc25.noarch.rpm
###
Name of package: `securedrop-workstation-dom0-config`, version 0.6.1
Note that I added the unsigned RPM as a separate commit for the record.
> Release securedrop workstation dom0 config 0.6.1

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.6.1-1.fc25.noarch.rpm
The CI build of #28 was legitimately failing because the RPM package signature was incorrect. (The wrong key was used.)
This reverts commit e929a38e6512b108f34c878b6debe5bbcd2839a4.
See https://github.com/freedomofpress/securedrop-workstation-prod-rpm-packages-lfs/pull/28
> Revert "add securedrop-workstation-dom0-config 0.6.1 signed package"

- workstation/dom0/f25/securedrop-workstation-dom0-config-0.6.2-1.fc25.noarch.rpm
###
Name of package: `securedrop-workstation-dom0-config 0.6.2`
Same artifact from https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/33 was resigned with the prod signing key.
In addition:
> Release securedrop-workstation-dom0-config 0.6.2 to yum prod

- workstation/dom0/f32/securedrop-workstation-dom0-config-0.7.0-1.fc32.noarch.rpm
Promoting [package on yum-test ](https://yum-test.securedrop.org/workstation/dom0/f32/securedrop-workstation-dom0-config-0.7.0-1.fc32.noarch.rpm) to prod (see https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/38).
Package being released: `securedrop-workstation-dom0-config 0.7.0`
Package tag: https://github.com/freedomofpress/securedrop-workstation/releases/tag/0.7.0
Build logs: (see https://github.com/freedomofpress/securedrop-workstation-dev-rpm-packages-lfs/pull/38)
Prod signing key used to sign package and tag: https://github.com/freedomofpress/securedrop-workstation-prod-rpm-packages-lfs/blob/HEAD/pubkeys/prod.key
Release tracking issue: https://github.com/freedomofpress/securedrop-workstation-prod-rpm-packages-lfs/issues/33
> * Download the signed …
> promote securedrop-workstation-dom0-config 0.7.0 to prod

- .circleci/config.yml
- README.md
Not a package PR, so removing the usual checklist for that -- rather, this updates references to the name of this repo itself per our rename plan in https://github.com/freedomofpress/securedrop-builder/issues/304. There's a README change and a CircleCI change, and the latter will fail at the moment because the rename has not happened yet, but should work later today after that is done.
> Update yum prod LFS repo name

- workstation/dom0/f32/securedrop-workstation-dom0-config-0.8.0-1.fc32.noarch.rpm
Refs <https://github.com/freedomofpress/securedrop-workstation/issues/866>.
###
Name of package: securedrop-workstation-dom0-config
> Add securedrop-workstation-dom0-config 0.8.0

- workstation/dom0/f32/qubes-template-securedrop-workstation-bullseye-4.1-202306151618.noarch.rpm
###
Towards https://github.com/freedomofpress/securedrop-workstation/issues/888 
Closes https://github.com/freedomofpress/securedrop-workstation/issues/887
Name of package: qubes-template-securedrop-workstation-bullseye-4.1-202306151618
> Deploy updated qubes template to yum-qa

- workstation/dom0/f32/qubes-template-securedrop-workstation-bullseye-4.1-202306151618.noarch.rpm
Fixes https://github.com/freedomofpress/securedrop-workstation/issues/888
Name of package: qubes-template-securedrop-workstation-bullseye-4.1-202306151618
As this merges `release` into `main`, this is essentially a package promotion PR, please see https://github.com/freedomofpress/securedrop-yum-prod/pull/43 for build log and other information about the actual package.
> Release qubes-template-securedrop-workstation-bullseye-4.1-202306151618

- workstation/dom0/f32/securedrop-workstation-dom0-config-0.9.0-1.fc32.noarch.rpm
###
Name of package:
securedrop-workstation-dom0-config-0.9.0-1.fc32.noarch.rpm
> Release SecureDrop Workstation 0.9.0

- workstation/dom0/f32/securedrop-workstation-dom0-config-0.10.0-1.fc32.noarch.rpm
###
Name of package:
securedrop-workstation-dom0-config-0.10.0-1.fc32.noarch.rpm
> SecureDrop Workstation 0.10.0

- workstation/dom0/f32/securedrop-workstation-dom0-config-0.11.0-1.fc32.noarch.rpm
###
securedrop-workstation-dom0-config
Package is  available on yum-qa.securedrop.org.
Before approval and merge, preflight tests are required for the following:
See https://github.com/freedomofpress/securedrop-workstation/issues/999 for more information and a test plan.
> Release securedrop-workstation-dom0-config 0.11.0

- workstation/dom0/f32/securedrop-workstation-dom0-config-0.11.1-1.fc32.noarch.rpm
###
Name of package: securedrop-workstation-dom0-config 0.11.1
Refs https://github.com/freedomofpress/securedrop-workstation/issues/1057
> Add securedrop-workstation-dom0-config-0.11.1

- workstation/dom0/f37/securedrop-workstation-dom0-config-1.0.0-1.fc37.noarch.rpm
###
Name of package: securedrop-workstation-dom0-config
Refs https://github.com/freedomofpress/securedrop-workstation/issues/1103
> Add securedrop-workstation-dom0-config 1.0.0 RPM

- workstation/dom0/f37/securedrop-workstation-dom0-config-1.0.2-1.fc37.noarch.rpm
###
Name of package: securedrop-workstation-dom0-config
> SecureDrop Workstation 1.0.2

- workstation/dom0/f37/securedrop-workstation-dom0-config-1.1.0-1.fc37.noarch.rpm
###
Name of package: securedrop-workstation-dom0-config
Refs: https://github.com/freedomofpress/securedrop-workstation/issues/1209
> SecureDrop Workstation 1.1.0

- workstation/dom0/f37/securedrop-workstation-dom0-config-1.1.1-1.fc37.noarch.rpm
###
Name of package: securedrop-workstation-dom0-config 1.1.1
> Release SecureDrop Workstation 1.1.1

- .github/workflows/ci.yml
- scripts/check.py
#61 proposes to have reviewers check that:
https://github.com/freedomofpress/securedrop-yum-prod/blob/b5e9cae42fdb45c067f2a71ffe965f3bf2af6ec9/.github/pull_request_template.md?plain=1#L10
I think this is worth automating just one step further, indeed a step towards automating it entirely as anticipated by freedomofpress/securedrop-builder#418, as we already do for `.deb` packages from their `.buildinfo` files.
> ci: output the hashes of all RPM packages without their signatures
